import { NewPlace } from "../types/place.types";

const p = (
  name: string,
  location: string,
  lat: number,
  lng: number,
  category: NewPlace["category"],
  tags: string[],
  noteGeneral: string,
  noteMustOrder = "",
  noteAvoid = "",
  extraFields: Record<string, string> = {},
  sourceUrl = "",
  lastVisitedAt: string | null = null
): NewPlace => ({
  name,
  location,
  latitude: lat,
  longitude: lng,
  category,
  tags,
  noteGeneral,
  noteMustOrder,
  noteAvoid,
  extraFields,
  sourceUrl,
  lastVisitedAt,
});

export const SEED_PLACES: NewPlace[] = [
  // ── Dining (15) ──
  p("Anand Bhavan", "Pulluvazhy, Kerala", 10.0803, 76.491, "Dining", ["Visited"], "Ample parking space", "Ghee Roast", "Coffee"),
  p("Thalassery Biryani House", "Thalassery, Kannur, Kerala", 11.7467, 75.4894, "Dining", ["Visited", "Legendary"], "Three generations of Malabar cuisine. Cash preferred, card machine unreliable. Last orders at 9:30 PM.", "Thalassery Dum Biryani, Malabar Chicken Curry, Pathiri with Egg Roast, Sulaimani Tea", "Fish fry on Mondays, upstairs seating during peak lunch hours"),
  p("Meghana Foods", "Residency Road, Bangalore", 12.9716, 77.5946, "Dining", ["Visited"], "Always crowded, expect 20-30 min wait during peak hours. Biryani portions are generous.", "Andhra Chicken Biryani, Meals", "Starters are average", {}, "https://maps.app.goo.gl/meghana"),
  p("The Velvet Onion", "Lower East Side, NYC", 40.715, -73.984, "Dining", ["Legendary"], "Upscale but not pretentious. Reservation recommended for weekends.", "Truffle Risotto, Wagyu Sliders", "House wine is overpriced"),
  p("Saravana Bhavan", "Connaught Place, New Delhi", 28.6315, 77.2167, "Dining", ["Visited"], "Iconic South Indian chain. Consistent quality across branches.", "Mini Tiffin Combo, Filter Coffee", "", {}, "https://maps.app.goo.gl/saravana"),
  p("Nasi Kandar Pelita", "Jalan Ampang, Kuala Lumpur", 3.1579, 101.7117, "Dining", ["To Visit"], "Open 24 hours. Popular with locals and tourists alike."),
  p("Dishoom", "Shoreditch, London", 51.5246, -0.0772, "Dining", ["Visited", "Legendary"], "Bombay-inspired cafe. Go early or expect long queues.", "Black Daal, Bacon Naan Roll", "Skip the lamb chops"),
  p("Warung Babi Guling Ibu Oka", "Ubud, Bali", -8.5069, 115.2624, "Dining", ["To Visit"], "Anthony Bourdain recommended. Best suckling pig in Bali."),
  p("Karavalli", "The Gateway Hotel, Bangalore", 12.9611, 77.6387, "Dining", ["Visited"], "Coastal Karnataka cuisine in a beautiful open-air setting.", "Mangalore Fish Curry, Appam", "Desserts are underwhelming"),
  p("Pho Thin", "Lo Duc Street, Hanoi", 21.0118, 105.8564, "Dining", ["To Visit"], "Famous for dry pho. Tiny shop, communal seating. Cash only."),
  p("Koshy's", "St Marks Road, Bangalore", 12.9735, 77.6033, "Dining", ["Visited"], "Heritage restaurant since 1940. Great for breakfast.", "Eggs to order, Toast, Filter Coffee", "Service can be slow"),
  p("Din Tai Fung", "Orchard Road, Singapore", 1.3021, 103.8372, "Dining", ["Visited"], "Legendary soup dumplings. Open kitchen is fun to watch.", "Xiao Long Bao, Truffle Dumplings", "Fried rice is average"),
  p("Mavalli Tiffin Rooms", "Lalbagh Road, Bangalore", 12.9509, 77.5847, "Dining", ["Visited", "Legendary"], "Iconic since 1924. Queue up early for weekend breakfast.", "Masala Dosa, Rava Idli, Kesari Bath", ""),
  p("Al Faham Restaurant", "Calicut, Kerala", 11.2588, 75.7804, "Dining", ["Visited"], "Best Al Faham chicken in Calicut.", "Al Faham Full, Kuboos", ""),
  p("Trattoria da Luigi", "Trastevere, Rome", 41.8879, 12.4699, "Dining", ["To Visit"], "Hidden gem away from tourist crowds. Handmade pasta daily."),

  // ── Cafe (12) ──
  p("Blue Tokai Coffee", "Koramangala, Bangalore", 12.9352, 77.6245, "Cafe", ["Visited"], "Great single-origin pour-overs. Laptop-friendly.", "Vienna Latte, Cold Brew", "Gets noisy after 5 PM", { mustTry: "Single Origin Pour Over", avoid: "Weekday evenings" }),
  p("Third Wave Coffee", "Indiranagar, Bangalore", 12.9784, 77.6408, "Cafe", ["Visited"], "Consistent quality across branches. Good for work sessions.", "Hazelnut Latte", "", { mustTry: "Hazelnut Latte" }),
  p("Cafe Mondegar", "Colaba, Mumbai", 18.9217, 72.8318, "Cafe", ["Visited"], "Iconic Mumbai cafe with Mario Miranda art on the walls.", "", "", { mustTry: "Cold Coffee" }),
  p("The Roastery by Nomu", "Jubilee Hills, Hyderabad", 17.4326, 78.4071, "Cafe", ["To Visit"], "Specialty roastery with single-origin beans from India and Ethiopia."),
  p("Birdsong Cafe", "Bandra, Mumbai", 19.0596, 72.8295, "Cafe", ["Visited", "Legendary"], "Beautiful interiors, great breakfast menu. Reservations needed on weekends.", "Eggs Benedict, Matcha Latte", "Parking is terrible", { mustTry: "Eggs Benedict", avoid: "Weekend lunch without reservation" }),
  p("Stumptown Coffee", "Downtown Portland, Oregon", 45.5231, -122.6765, "Cafe", ["To Visit"], "OG third-wave coffee roasters."),
  p("Coffee by Di Bella", "Lower Parel, Mumbai", 18.9929, 72.8265, "Cafe", ["Visited"], "Italian-style espresso done well.", "Flat White", "", { mustTry: "Flat White" }),
  p("Hatti Kaapi", "Malleshwaram, Bangalore", 13.0035, 77.5691, "Cafe", ["Visited", "Legendary"], "Traditional filter coffee at its best. Standing-only.", "Filter Coffee", "", { mustTry: "Filter Kaapi" }),
  p("%Arabica", "Higashiyama, Kyoto", 35.0016, 135.7813, "Cafe", ["To Visit"], "Minimalist cafe with views of Yasaka Pagoda. Instagram-famous but actually good."),
  p("Cafe Lota", "Pragati Maidan, New Delhi", 28.6129, 77.2433, "Cafe", ["Visited"], "Inside the Crafts Museum. Beautiful outdoor seating.", "Chai, Samosa", "", { mustTry: "Masala Chai" }),
  p("Dyu Art Cafe", "Koramangala, Bangalore", 12.9343, 77.6267, "Cafe", ["Visited"], "Art gallery meets cafe. Quiet reading spot.", "Cappuccino, Cheesecake", "", { mustTry: "New York Cheesecake" }),
  p("Kopi Luwak Cafe", "Ubud, Bali", -8.5087, 115.2559, "Cafe", ["To Visit"], "Try the famous civet coffee. Ethical sourcing verified."),

  // ── Tourist Attraction (12) ──
  p("Cloud's End Peak", "Mussoorie, Uttarakhand", 30.4598, 78.0644, "Tourist Attraction", ["To Visit"], "Remote viewpoint. Trail gets steep in the last km. Carry water.", "", "", { entryFee: "Free", trekTime: "2.5 hours one way", bestSeason: "October to March" }),
  p("Athirappilly Falls", "Thrissur, Kerala", 10.2856, 76.5699, "Tourist Attraction", ["Visited", "Legendary"], "Niagara of India. Best during monsoon season.", "", "", { entryFee: "40 INR", trekTime: "30 min walk", bestSeason: "June to September" }, "https://maps.app.goo.gl/athirappilly"),
  p("Hampi Ruins", "Hampi, Karnataka", 15.335, 76.462, "Tourist Attraction", ["Visited"], "UNESCO World Heritage. Hire a bicycle to explore. Carry sun protection.", "", "", { entryFee: "600 INR for foreigners, 40 INR for Indians", trekTime: "Full day needed", bestSeason: "October to February" }),
  p("Meenakshi Temple", "Madurai, Tamil Nadu", 9.9195, 78.1193, "Tourist Attraction", ["Visited"], "Stunning Dravidian architecture. Go during evening pooja for the best experience.", "", "", { entryFee: "Free", bestSeason: "Year round, avoid April-May heat" }),
  p("Valley of Flowers", "Chamoli, Uttarakhand", 30.7283, 79.605, "Tourist Attraction", ["To Visit"], "UNESCO site. Over 600 species of wildflowers. Permits required.", "", "", { entryFee: "150 INR + 600 INR trek permit", trekTime: "5-6 hours from Ghangaria", bestSeason: "July to September" }),
  p("Angkor Wat", "Siem Reap, Cambodia", 13.4125, 103.867, "Tourist Attraction", ["To Visit"], "Largest religious monument in the world. Go for sunrise at the reflecting pool.", "", "", { entryFee: "37 USD for 1 day", bestSeason: "November to February" }),
  p("Dudhsagar Falls", "Goa-Karnataka border", 15.3144, 74.3143, "Tourist Attraction", ["Visited"], "Milky white waterfall on the railway track. Jeep ride from Collem is an adventure.", "", "", { entryFee: "400 INR jeep + 100 INR entry", trekTime: "30 min from drop point", bestSeason: "September to December" }),
  p("Jog Falls", "Shimoga, Karnataka", 14.2295, 74.8125, "Tourist Attraction", ["Visited"], "Second highest plunge waterfall in India. Breathtaking during monsoon.", "", "", { entryFee: "Free", bestSeason: "August to October" }),
  p("Rann of Kutch", "Kutch, Gujarat", 23.7337, 69.8597, "Tourist Attraction", ["To Visit"], "White salt desert that stretches to the horizon. Visit during Rann Utsav.", "", "", { entryFee: "100 INR", bestSeason: "November to February" }),
  p("Coorg Abbey Falls", "Madikeri, Karnataka", 12.4589, 75.7348, "Tourist Attraction", ["Visited"], "Beautiful waterfall surrounded by coffee plantations.", "", "", { entryFee: "15 INR", trekTime: "10 min from parking", bestSeason: "June to September" }),
  p("Rishikesh Laxman Jhula", "Rishikesh, Uttarakhand", 30.1256, 78.3219, "Tourist Attraction", ["Visited"], "Iconic suspension bridge over the Ganges. Great starting point for rafting.", "", "", { entryFee: "Free", bestSeason: "September to November" }),
  p("Taj Mahal", "Agra, Uttar Pradesh", 27.1751, 78.0421, "Tourist Attraction", ["Visited", "Legendary"], "Go at sunrise. Friday is closed. Book tickets online to skip queues.", "", "", { entryFee: "50 INR Indians, 1100 INR foreigners", bestSeason: "October to March" }),

  // ── Stay (10) ──
  p("Zostel Manali", "Old Manali, Himachal Pradesh", 32.2432, 77.1892, "Stay", ["Visited"], "Budget hostel by the river. Great common area for meeting travelers.", "", "", { priceRange: "600-1200 INR/night", checkInInfo: "Check-in 1 PM, Check-out 11 AM" }),
  p("Zostel Coorg", "Madikeri, Karnataka", 12.4208, 75.7397, "Stay", ["Visited"], "Hilltop location with valley views. Bonfires every evening.", "", "", { priceRange: "800-1500 INR/night", checkInInfo: "Check-in 2 PM" }),
  p("The Hosteller Jaipur", "MI Road, Jaipur", 26.9124, 75.7873, "Stay", ["Visited"], "Clean, well-maintained. Walking distance to Hawa Mahal.", "", "", { priceRange: "500-900 INR/night", checkInInfo: "Check-in 12 PM" }),
  p("Gokulam Grand", "Mysore, Karnataka", 12.3051, 76.6551, "Stay", ["Visited"], "Mid-range hotel near the palace. Good restaurant.", "", "", { priceRange: "3000-5000 INR/night", checkInInfo: "Check-in 2 PM, Check-out 12 PM" }),
  p("Backpackers Hostel Goa", "Anjuna, Goa", 15.5736, 73.7413, "Stay", ["Visited"], "Party hostel. Pool and rooftop bar. Not for light sleepers.", "", "", { priceRange: "700-1000 INR/night", checkInInfo: "Flexible" }),
  p("Windflower Resort Coorg", "Suntikoppa, Karnataka", 12.4626, 75.8073, "Stay", ["To Visit"], "Luxury resort in the middle of a coffee estate.", "", "", { priceRange: "12000-18000 INR/night", checkInInfo: "Check-in 2 PM" }),
  p("OYO Townhouse MG Road", "MG Road, Bangalore", 12.9756, 77.6065, "Stay", ["Visited"], "Decent budget option for transit stays.", "", "", { priceRange: "1500-2500 INR/night", checkInInfo: "24hr check-in" }),
  p("Capsule Hotel Mumbai", "Andheri East, Mumbai", 19.1136, 72.8697, "Stay", ["Visited"], "Japanese-style capsule hotel near the airport. Great for layovers.", "", "", { priceRange: "1200-1800 INR/night", checkInInfo: "24hr" }),
  p("Taj Lake Palace", "Udaipur, Rajasthan", 24.5754, 73.6805, "Stay", ["To Visit"], "Floating palace hotel on Lake Pichola. Bucket list stay.", "", "", { priceRange: "35000+ INR/night", checkInInfo: "Boat transfer from jetty" }),
  p("Treebo Trend Blue Moon", "HSR Layout, Bangalore", 12.9116, 77.6389, "Stay", ["Visited"], "Clean rooms, good wifi. Near HSR food street.", "", "", { priceRange: "1800-2500 INR/night", checkInInfo: "Check-in 12 PM" }),

  // ── Viewpoint (10) ──
  p("Nandi Hills Sunrise", "Chikkaballapur, Karnataka", 13.3702, 77.6835, "Viewpoint", ["Visited", "Legendary"], "Go before 5:30 AM. Extremely crowded on weekends.", "", "", { bestTime: "5:00-6:30 AM sunrise", trekDuration: "Drive up, no trek" }, "https://maps.app.goo.gl/nandi"),
  p("Skandagiri Night Trek", "Chikkaballapur, Karnataka", 13.3583, 77.6894, "Viewpoint", ["Visited"], "Night trek starting at 2 AM. Sunrise at summit is spectacular.", "", "", { bestTime: "2 AM start, 5:30 AM sunrise", trekDuration: "2.5 hours uphill" }),
  p("Coorg Raja's Seat", "Madikeri, Karnataka", 12.4203, 75.738, "Viewpoint", ["Visited"], "Sunset viewpoint with a garden. Musical fountain in the evening.", "", "", { bestTime: "4:30-6:00 PM sunset", trekDuration: "No trek, accessible by road" }),
  p("Mullayanagiri Peak", "Chikmagalur, Karnataka", 13.3893, 75.7228, "Viewpoint", ["Visited"], "Highest peak in Karnataka. Misty conditions most mornings.", "", "", { bestTime: "Early morning", trekDuration: "45 min from parking" }),
  p("Tiger Hill", "Darjeeling, West Bengal", 27.0126, 88.2688, "Viewpoint", ["To Visit"], "Famous for Kanchenjunga sunrise view. Book jeep the night before.", "", "", { bestTime: "4 AM departure for sunrise", trekDuration: "Drive up" }),
  p("Triund Trek", "McLeodganj, Himachal Pradesh", 32.2521, 76.3218, "Viewpoint", ["To Visit"], "Easy overnight trek with Dhauladhar range views.", "", "", { bestTime: "Sunset and sunrise", trekDuration: "3-4 hours from Galu Devi temple" }),
  p("Kodaikanal Pillar Rocks", "Kodaikanal, Tamil Nadu", 10.2167, 77.4667, "Viewpoint", ["Visited"], "Three granite pillars rising 400 feet. Misty and dramatic.", "", "", { bestTime: "Morning before fog", trekDuration: "5 min walk from parking" }),
  p("Ponmudi Hilltop", "Thiruvananthapuram, Kerala", 8.7606, 77.1195, "Viewpoint", ["Visited"], "22 hairpin bends to reach the top. Views of tea estates.", "", "", { bestTime: "Morning", trekDuration: "Short walks at top" }),
  p("Kudremukh Peak", "Chikmagalur, Karnataka", 13.2465, 75.2557, "Viewpoint", ["To Visit"], "Horse-face shaped peak. Permit required from forest dept.", "", "", { bestTime: "October to February", trekDuration: "6-7 hours round trip" }),
  p("Sakleshpur Green Route", "Hassan, Karnataka", 12.9412, 75.7852, "Viewpoint", ["Visited"], "Railway track trek through tunnels and bridges. Unique experience.", "", "", { bestTime: "Monsoon for greenery", trekDuration: "4-5 hours one way" }),

  // ── Shopping (10) ──
  p("Commercial Street", "Shivaji Nagar, Bangalore", 12.9821, 77.6074, "Shopping", ["Visited"], "Haggle for 30-40% off. Best for clothing and accessories.", "", "", { whatToBuy: "Ethnic wear, junk jewelry, leather goods", priceRange: "Budget-friendly" }),
  p("Chickpet Silk Market", "Chickpet, Bangalore", 12.9667, 77.5762, "Shopping", ["Visited"], "Wholesale silk sarees. Go on weekdays to avoid crowds.", "", "", { whatToBuy: "Silk sarees, fabrics", priceRange: "2000-15000 INR per saree" }),
  p("Lajpat Nagar Market", "Lajpat Nagar, New Delhi", 28.5688, 77.2389, "Shopping", ["To Visit"], "Known for wedding shopping and street food.", "", "", { whatToBuy: "Bridal wear, home decor", priceRange: "Budget to mid-range" }),
  p("Colaba Causeway", "Colaba, Mumbai", 18.9178, 72.8317, "Shopping", ["Visited"], "Antiques, jewelry, and hippie clothing. Great for souvenirs.", "", "", { whatToBuy: "Silver jewelry, handicrafts, books", priceRange: "Budget" }),
  p("Arpora Saturday Night Market", "Arpora, Goa", 15.5584, 73.7658, "Shopping", ["Visited"], "Live music, food stalls, and shopping under the stars.", "", "", { whatToBuy: "Boho clothing, spices, cashews", priceRange: "Mid-range" }),
  p("Mysore Devaraja Market", "Mysore, Karnataka", 12.3107, 76.6559, "Shopping", ["Visited"], "150+ year old market. Sandalwood, spices, and flowers.", "", "", { whatToBuy: "Mysore Pak, sandalwood, incense", priceRange: "Budget" }),
  p("Brigade Road", "Brigade Road, Bangalore", 12.9716, 77.6077, "Shopping", ["Visited"], "Mix of branded stores and street shopping.", "", "", { whatToBuy: "Clothing, shoes, accessories", priceRange: "Mid-range" }),
  p("Chandni Chowk", "Old Delhi", 28.6507, 77.2334, "Shopping", ["To Visit"], "One of the oldest markets in India. Overwhelming but worth it.", "", "", { whatToBuy: "Electronics, fabrics, street food", priceRange: "Budget" }),
  p("Chatuchak Weekend Market", "Bangkok, Thailand", 13.7999, 100.5503, "Shopping", ["To Visit"], "15,000+ stalls. Go early to beat the heat.", "", "", { whatToBuy: "Vintage clothing, art, street food", priceRange: "Budget" }),
  p("MG Road Metro Walk", "MG Road, Bangalore", 12.9753, 77.6062, "Shopping", ["Visited"], "Upscale shopping street. Good for window shopping.", "", "", { whatToBuy: "Branded clothing, books at Blossoms", priceRange: "Premium" }),

  // ── Fuel/EV (8) ──
  p("HP Pump NH66", "Kalamassery, Ernakulam", 10.0527, 76.3214, "Fuel/EV", [], "Clean restroom and small cafe. Open 24 hours.", "", "", { fuelTypes: "Petrol, Diesel, EV 50kW DC", amenities: "Restroom, cafe, air pump" }),
  p("IOCL Pump Outer Ring Road", "Marathahalli, Bangalore", 12.9591, 77.6971, "Fuel/EV", [], "Usually less crowded than Shell next door.", "", "", { fuelTypes: "Petrol, Diesel", amenities: "Restroom, ATM nearby" }),
  p("Shell Pump Hosur Road", "Electronic City, Bangalore", 12.8456, 77.6603, "Fuel/EV", [], "Premium fuel available. Clean facilities.", "", "", { fuelTypes: "Petrol, Diesel, V-Power", amenities: "Restroom, convenience store" }),
  p("Ather Grid Station Forum Mall", "Koramangala, Bangalore", 12.9352, 77.6126, "Fuel/EV", [], "Fast charging for Ather scooters. Inside mall parking.", "", "", { fuelTypes: "EV Ather Grid", amenities: "Mall access while charging" }),
  p("Tata EV Charging Hub", "Whitefield, Bangalore", 12.9698, 77.7499, "Fuel/EV", [], "Multiple CCS2 chargers. Rarely occupied.", "", "", { fuelTypes: "EV CCS2 60kW, Type 2 AC", amenities: "Cafe next door" }),
  p("BPC Pump Kozhikode", "Mavoor Road, Calicut", 11.2515, 75.7763, "Fuel/EV", [], "Reliable pump near railway station.", "", "", { fuelTypes: "Petrol, Diesel", amenities: "Restroom, air, water" }),
  p("ChargeZone Station", "Indiranagar, Bangalore", 12.9784, 77.6408, "Fuel/EV", [], "Universal EV charging. App-based payment.", "", "", { fuelTypes: "EV CCS2, CHAdeMO, Type 2", amenities: "Covered parking" }),
  p("HP Green R Pump", "NICE Road, Bangalore", 12.9066, 77.5151, "Fuel/EV", [], "Highway pump with good food court.", "", "", { fuelTypes: "Petrol, Diesel, EV", amenities: "Food court, restroom, air pump" }),

  // ── W.C (8) ──
  p("MG Road Metro Restroom", "MG Road Metro Exit 2, Bangalore", 12.9756, 77.6065, "W.C", [], "Inside metro station, past ticket counter on left.", "", "", { cleanliness: "Clean, maintained regularly", access: "Free with metro ticket, else 5 INR" }),
  p("Lulu Mall Public WC", "Edappally, Kochi", 10.0274, 76.3084, "W.C", [], "Clean facilities on every floor.", "", "", { cleanliness: "Very clean", access: "Free" }),
  p("Forum Mall Restroom", "Koramangala, Bangalore", 12.9345, 77.6127, "W.C", [], "Ground floor near food court.", "", "", { cleanliness: "Clean", access: "Free" }),
  p("KSRTC Bus Stand WC", "Mysore, Karnataka", 12.2958, 76.6394, "W.C", [], "Paid restroom. Basic but functional.", "", "", { cleanliness: "Average", access: "10 INR" }),
  p("Airport Terminal 2 WC", "Kempegowda Airport, Bangalore", 13.1989, 77.7068, "W.C", [], "International terminal. Excellent facilities with showers.", "", "", { cleanliness: "Excellent", access: "Free" }),
  p("Sulabh Shauchalaya", "Connaught Place, New Delhi", 28.6315, 77.219, "W.C", [], "Iconic public toilet chain. Reliable in major cities.", "", "", { cleanliness: "Good", access: "5 INR" }),
  p("Phoenix Mall WC", "Whitefield, Bangalore", 12.9975, 77.6961, "W.C", [], "All floors have clean restrooms.", "", "", { cleanliness: "Very clean", access: "Free" }),
  p("Railway Station WC", "Ernakulam Junction, Kerala", 9.9816, 76.2999, "W.C", [], "Platform 1 has the better maintained restroom.", "", "", { cleanliness: "Average", access: "5 INR" }),

  // ── Other (15) ──
  p("Cubbon Park", "Kasturba Road, Bangalore", 12.9763, 77.5929, "Other", ["Visited", "Legendary"], "Green lung of Bangalore. Great for morning walks and reading. Dogs allowed."),
  p("Lalbagh Botanical Garden", "Lalbagh, Bangalore", 12.9507, 77.5848, "Other", ["Visited"], "200+ year old garden. Glass house flower shows twice a year."),
  p("Marine Drive", "Mumbai", 18.9432, 72.8235, "Other", ["Visited"], "Queen's Necklace at night. Best at sunset with cutting chai from a street vendor."),
  p("Connaught Place", "Central Delhi", 28.6315, 77.2167, "Other", ["Visited"], "Colonial-era market area. Good for aimless walking and people-watching."),
  p("Fort Kochi Beach", "Fort Kochi, Kerala", 9.9676, 76.2428, "Other", ["Visited"], "Chinese fishing nets at sunset. Art galleries and cafes nearby."),
  p("Pondicherry Promenade", "White Town, Pondicherry", 11.9344, 79.8347, "Other", ["Visited"], "French Quarter by the sea. Car-free on Sunday mornings."),
  p("Decathlon Sarjapur", "Sarjapur Road, Bangalore", 12.9087, 77.6685, "Other", ["Visited"], "Go-to for affordable sports gear. Huge store with trial zones."),
  p("Blossoms Book House", "Church Street, Bangalore", 12.9748, 77.6072, "Other", ["Visited", "Legendary"], "Three floors of second-hand books. You could spend an entire day here."),
  p("National Gallery Modern Art", "Palace Road, Bangalore", 12.9884, 77.5894, "Other", ["To Visit"], "Permanent collection of Indian modern art. Beautiful heritage building."),
  p("Yoga Barn", "Ubud, Bali", -8.5086, 115.2615, "Other", ["To Visit"], "Drop-in yoga and meditation classes. Beautiful bamboo structure."),
  p("Decathlon Whitefield", "Whitefield, Bangalore", 12.9778, 77.7251, "Other", ["Visited"], "Smaller than Sarjapur branch but less crowded."),
  p("RV College Ground", "RV Vidyaniketan, Bangalore", 12.9236, 77.4986, "Other", ["Visited"], "Open ground for evening jogging. Usually empty after 6 PM."),
  p("Ulsoor Lake", "Halasuru, Bangalore", 12.9822, 77.6191, "Other", ["Visited"], "Boating available on weekends. Nice walking path around the lake."),
  p("Mantri Square Mall", "Malleshwaram, Bangalore", 13.0106, 77.5701, "Other", [], "Large mall with good food court and movie theater."),
  p("VV Puram Food Street", "VV Puram, Bangalore", 12.9461, 77.577, "Other", ["Visited", "Legendary"], "Bangalore's best street food street. Open evenings only. Try everything."),
];
